class Commands:
    LEECH = "leech@TorToolkitYtbot"
    PURGE = "purge@TorToolkitYtbot"
    PAUSEALL = "pauseall@TorToolkitYtbot"
    RESUMEALL = "resumeall@TorToolkitYtbot"
    STATUS = "status@TorToolkitYtbot"
    SETTINGS = "settings@TorToolkitYtbot"
    EXEC = "exec@TorToolkitYtbot"
    UPLOAD = "upload@TorToolkitYtbot"
    YTDL = "ytdl@TorToolkitYtbot"
    PYTDL = "pytdl@TorToolkitYtbot"
    ABOUT = "about@TorToolkitYtbot"
    GETLOGS = "getlogs@TorToolkitYtbot"
    SERVER = "server@TorToolkitYtbot"
    USERSETTINGS = "usetting@TorToolkitYtbot"
    INSTADL = "instadl@TorToolkitYtbot"
